<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<UserSecretsId>f8fc0ae3-a29b-47d6-b0c2-97a2ebb53a91</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\Snet.Yolo.Api.Shared\Program.cs" Pack="true" PackagePath="\" />
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\appsettings.json" Pack="true" PackagePath="\">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\appsettings.Development.json" Pack="true" PackagePath="\">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.10" />
		<PackageReference Include="YoloDotNet.ExecutionProvider.Cpu" Version="1.1.0" />
		<PackageReference Include="Snet.Yolo.Server" Version="26.211.1" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="Dockerfile">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<Import Project="..\Snet.Yolo.Api.Shared\Snet.Yolo.Api.Shared.projitems" Label="Shared" />

</Project>
